# your domain
domain: proxypool-wing0110210317.cloud.okteto.net
port:  12580

# source list file
source-files:
  # use local file
  # - /proxypool-src/conf/proxypool/source.yaml
  # use web file
  - https://dl.huppygovip.repl.co/proxypool/source.yaml

# ======= 可选项，留空使用default值  =======

# postgresql database info
database_url: "postgres://postgres:xiaoling3579@39.99.249.150:5846/postgres"

# interval between each crawling
crawl-interval:       # v0.5.x default 60 (minutes)
crontime:             # v0.4.x default 60 (minutes). Deprecated in the newest version

# speed test
speedtest: true         # default false. Warning: this will consume large network resources.
speedtest-interval: 15  # default 720 (min)
connection: 10          # default 5. The number of speed test connections simultaneously
timeout: 5              # default 10 (seconds).
## active proxy speed test
active-interval: 15     # default 60 (min)
active-frequency: 20    # default 100 (requests per interval)
active-max-number: 20   # default 100. If more than this number of active proxies, the extra will be deprecated by speed

# cloudflare api
cf_email: ""
cf_key: ""
